@echo off
REM Inkscape CLI batch export — generated by Game Asset Pipeline
REM Exports SVGs to PNG at multiple DPIs
set INKSCAPE=inkscape
%INKSCAPE% --export-filename="output\ui_assets\health_bar_72dpi.png" --export-dpi=72 "output\ui_assets\health_bar.svg"
%INKSCAPE% --export-filename="output\ui_assets\health_bar_144dpi.png" --export-dpi=144 "output\ui_assets\health_bar.svg"
%INKSCAPE% --export-filename="output\ui_assets\health_bar_288dpi.png" --export-dpi=288 "output\ui_assets\health_bar.svg"
%INKSCAPE% --export-filename="output\ui_assets\mana_bar_72dpi.png" --export-dpi=72 "output\ui_assets\mana_bar.svg"
%INKSCAPE% --export-filename="output\ui_assets\mana_bar_144dpi.png" --export-dpi=144 "output\ui_assets\mana_bar.svg"
%INKSCAPE% --export-filename="output\ui_assets\mana_bar_288dpi.png" --export-dpi=288 "output\ui_assets\mana_bar.svg"
%INKSCAPE% --export-filename="output\ui_assets\xp_bar_72dpi.png" --export-dpi=72 "output\ui_assets\xp_bar.svg"
%INKSCAPE% --export-filename="output\ui_assets\xp_bar_144dpi.png" --export-dpi=144 "output\ui_assets\xp_bar.svg"
%INKSCAPE% --export-filename="output\ui_assets\xp_bar_288dpi.png" --export-dpi=288 "output\ui_assets\xp_bar.svg"
%INKSCAPE% --export-filename="output\ui_assets\inventory_slot_72dpi.png" --export-dpi=72 "output\ui_assets\inventory_slot.svg"
%INKSCAPE% --export-filename="output\ui_assets\inventory_slot_144dpi.png" --export-dpi=144 "output\ui_assets\inventory_slot.svg"
%INKSCAPE% --export-filename="output\ui_assets\inventory_slot_288dpi.png" --export-dpi=288 "output\ui_assets\inventory_slot.svg"
%INKSCAPE% --export-filename="output\ui_assets\dialog_box_72dpi.png" --export-dpi=72 "output\ui_assets\dialog_box.svg"
%INKSCAPE% --export-filename="output\ui_assets\dialog_box_144dpi.png" --export-dpi=144 "output\ui_assets\dialog_box.svg"
%INKSCAPE% --export-filename="output\ui_assets\dialog_box_288dpi.png" --export-dpi=288 "output\ui_assets\dialog_box.svg"
%INKSCAPE% --export-filename="output\ui_assets\minimap_frame_72dpi.png" --export-dpi=72 "output\ui_assets\minimap_frame.svg"
%INKSCAPE% --export-filename="output\ui_assets\minimap_frame_144dpi.png" --export-dpi=144 "output\ui_assets\minimap_frame.svg"
%INKSCAPE% --export-filename="output\ui_assets\minimap_frame_288dpi.png" --export-dpi=288 "output\ui_assets\minimap_frame.svg"
%INKSCAPE% --export-filename="output\ui_assets\tooltip_72dpi.png" --export-dpi=72 "output\ui_assets\tooltip.svg"
%INKSCAPE% --export-filename="output\ui_assets\tooltip_144dpi.png" --export-dpi=144 "output\ui_assets\tooltip.svg"
%INKSCAPE% --export-filename="output\ui_assets\tooltip_288dpi.png" --export-dpi=288 "output\ui_assets\tooltip.svg"
echo Done.
