"""
Sprite Generator — GIMP Script-Fu + Pillow Fallback
Generates character sprites, tile sets, and item icons.
Outputs GIMP batch scripts (.scm) for professional production
and Pillow-rendered previews for the web dashboard.
"""

import os
import json
import math
import random
from PIL import Image, ImageDraw, ImageFont, ImageFilter

# ─── GIMP SCRIPT-FU GENERATOR ──────────────────────────────────────────

GIMP_SPRITE_TEMPLATE = """; ============================================================
; GIMP Script-Fu: {name} Sprite Sheet Generator
; Auto-generated by Game Asset Pipeline
; Usage: gimp -i -b '(script-fu-load "{script_path}")' -b '(gimp-quit 0)'
; ============================================================

(define (generate-{safe_name}-sprites output-dir)
  (let* (
    (sprite-w {sprite_size})
    (sprite-h {sprite_size})
    (cols {cols})
    (rows {rows})
    (sheet-w (* sprite-w cols))
    (sheet-h (* sprite-h rows))
    (sheet (car (gimp-image-new sheet-w sheet-h RGB)))
    (layer (car (gimp-layer-new sheet sheet-w sheet-h RGBA-IMAGE "sprites" 100 LAYER-MODE-NORMAL)))
  )
  (gimp-image-insert-layer sheet layer 0 -1)

  ; Set foreground color for sprite base
  (gimp-context-set-foreground '({r} {g} {b}))

  ; Draw sprite frames
{frame_commands}

  ; Flatten and export
  (gimp-image-flatten sheet)
  (file-png-save RUN-NONINTERACTIVE sheet
    (car (gimp-image-get-active-drawable sheet))
    (string-append output-dir "/{name}_sheet.png")
    "{name}_sheet" 0 9 1 1 1 1 1)

  (gimp-image-delete sheet)
  )
)

; Execute
(generate-{safe_name}-sprites "{output_dir}")
"""

GIMP_FRAME_RECT = """  ; Frame: {frame_name} (col {col}, row {row})
  (gimp-image-set-active-layer sheet layer)
  (gimp-context-set-foreground '({r} {g} {b}))
  (gimp-edit-fill layer FILL-FOREGROUND)
  (gimp-image-select-rectangle sheet CHANNEL-OP-REPLACE {x} {y} {w} {h})
  (gimp-edit-bucket-fill layer FILL-FOREGROUND LAYER-MODE-NORMAL 100 0 FALSE 0 0)
  (gimp-selection-none sheet)
"""


def generate_gimp_scripts(config, output_dir):
    """Generate GIMP Script-Fu files for batch sprite processing."""
    scripts_dir = os.path.join(output_dir, "scripts", "gimp")
    os.makedirs(scripts_dir, exist_ok=True)

    sprite_size = config["pipeline_2d"]["sprite_size"]
    sprites = config["pipeline_2d"]["sprites"]
    palettes = config["palettes"]
    generated = []

    for sprite_def in sprites:
        name = sprite_def["name"]
        frames = sprite_def["frames"]
        palette_name = sprite_def.get("palette", "fantasy")
        palette = palettes.get(palette_name, palettes["fantasy"])
        color = palette["primary"]

        cols = min(len(frames), config["pipeline_2d"]["sprite_sheet_columns"])
        rows = math.ceil(len(frames) / cols)
        safe_name = name.replace("-", "_").replace(" ", "_")

        frame_commands = ""
        for i, frame in enumerate(frames):
            col = i % cols
            row = i // cols
            x = col * sprite_size
            y = row * sprite_size
            frame_commands += GIMP_FRAME_RECT.format(
                frame_name=frame, col=col, row=row,
                r=color[0], g=color[1], b=color[2],
                x=x, y=y, w=sprite_size, h=sprite_size
            )

        script_path = os.path.join(scripts_dir, f"{name}_sprites.scm")
        script_content = GIMP_SPRITE_TEMPLATE.format(
            name=name, safe_name=safe_name,
            sprite_size=sprite_size, cols=cols, rows=rows,
            r=color[0], g=color[1], b=color[2],
            frame_commands=frame_commands,
            script_path=script_path.replace("\\", "/"),
            output_dir=os.path.join(output_dir, "sprites").replace("\\", "/")
        )

        with open(script_path, "w") as f:
            f.write(script_content)

        generated.append({
            "type": "gimp_script",
            "name": f"{name}_sprites.scm",
            "path": script_path,
            "tool": "GIMP Script-Fu",
            "description": f"Sprite sheet generator for {name} character"
        })

    return generated


# ─── PILLOW FALLBACK RENDERER ──────────────────────────────────────────

def _draw_character_frame(draw, x, y, size, frame_name, color, variant=0):
    """Draw a single stylized character sprite frame."""
    cx, cy = x + size // 2, y + size // 2
    pad = size // 8

    r, g, b = color
    body_color = (r, g, b, 255)
    shadow_color = (max(0, r - 60), max(0, g - 60), max(0, b - 60), 255)
    highlight_color = (min(255, r + 40), min(255, g + 40), min(255, b + 40), 255)
    skin_color = (240, 200, 170, 255)
    outline_color = (20, 20, 30, 255)

    head_r = size // 6
    body_w = size // 4
    body_h = size // 3
    leg_w = size // 8
    leg_h = size // 4

    # Frame-specific offsets for animation feel
    bob = 0
    lean = 0
    arm_angle = 0
    if "walk" in frame_name:
        bob = int(math.sin(variant * math.pi / 2) * 2)
        lean = int(math.sin(variant * math.pi / 3) * 3)
    elif "attack" in frame_name:
        lean = variant * 4
        arm_angle = variant * 15
    elif "jump" in frame_name:
        bob = -4
    elif "fall" in frame_name:
        bob = 3
    elif "cast" in frame_name:
        arm_angle = -20 + variant * 30
    elif "shoot" in frame_name:
        lean = variant * 3

    # Shadow on ground
    draw.ellipse([cx - body_w, y + size - pad - 4, cx + body_w, y + size - pad + 2],
                 fill=(0, 0, 0, 40))

    # Legs
    lx1 = cx - leg_w - 2 + lean
    lx2 = cx + 2 + lean
    ly = cy + body_h // 2 + bob
    draw.rectangle([lx1, ly, lx1 + leg_w, ly + leg_h], fill=shadow_color, outline=outline_color, width=1)
    draw.rectangle([lx2, ly, lx2 + leg_w, ly + leg_h], fill=shadow_color, outline=outline_color, width=1)

    # Body
    bx = cx - body_w // 2 + lean
    by = cy - body_h // 3 + bob
    draw.rounded_rectangle([bx, by, bx + body_w, by + body_h],
                           radius=3, fill=body_color, outline=outline_color, width=1)
    # Highlight stripe
    draw.line([bx + 3, by + 3, bx + 3, by + body_h - 3], fill=highlight_color, width=1)

    # Arms
    ax_l = bx - leg_w
    ax_r = bx + body_w
    ay = by + 4 + bob
    draw.rectangle([ax_l, ay, ax_l + leg_w - 1, ay + body_h - 8], fill=body_color, outline=outline_color, width=1)
    draw.rectangle([ax_r, ay, ax_r + leg_w - 1, ay + body_h - 8], fill=body_color, outline=outline_color, width=1)

    # Head
    hx, hy = cx + lean, by - head_r + bob
    draw.ellipse([hx - head_r, hy - head_r, hx + head_r, hy + head_r],
                 fill=skin_color, outline=outline_color, width=1)
    # Eyes
    eye_y = hy - 1
    draw.rectangle([hx - 3, eye_y - 1, hx - 1, eye_y + 1], fill=outline_color)
    draw.rectangle([hx + 1, eye_y - 1, hx + 3, eye_y + 1], fill=outline_color)

    # Weapon/effect hints based on frame
    if "attack" in frame_name or "sword" in frame_name:
        draw.line([ax_r + leg_w, ay, ax_r + leg_w + 10 + lean, ay - 8],
                  fill=(200, 200, 210, 255), width=2)
    elif "cast" in frame_name:
        for i in range(3):
            spark_x = ax_r + leg_w + random.randint(2, 10)
            spark_y = ay - random.randint(0, 8)
            draw.ellipse([spark_x, spark_y, spark_x + 3, spark_y + 3],
                         fill=(255, 200, 50, 200))
    elif "shoot" in frame_name:
        draw.line([ax_r + leg_w, ay + 4, ax_r + leg_w + 12, ay + 4],
                  fill=(0, 220, 255, 255), width=2)


def _draw_tile(draw, x, y, size, tile_type, palette, variant=0):
    """Draw a terrain tile."""
    colors = {
        "grass": palette.get("grass", [60, 160, 60]),
        "stone": palette.get("stone", [140, 135, 125]),
        "water": palette.get("water", [50, 120, 200]),
        "lava": palette.get("lava", [255, 80, 20]),
        "metal_floor": palette.get("metal", palette.get("hull", [100, 105, 110]))
    }

    base = colors.get(tile_type, [128, 128, 128])
    r, g, b = base

    # Fill with slight variation per variant
    random.seed(hash(f"{tile_type}_{variant}"))
    for py in range(y, y + size, 4):
        for px in range(x, x + size, 4):
            vr = r + random.randint(-15, 15)
            vg = g + random.randint(-15, 15)
            vb = b + random.randint(-15, 15)
            draw.rectangle([px, py, px + 3, py + 3],
                           fill=(max(0, min(255, vr)), max(0, min(255, vg)), max(0, min(255, vb))))

    # Border/grid line
    draw.rectangle([x, y, x + size - 1, y + size - 1], outline=(0, 0, 0, 60), width=1)

    # Tile-specific decorations
    if tile_type == "grass":
        for _ in range(6):
            gx = x + random.randint(4, size - 8)
            gy = y + random.randint(size // 2, size - 6)
            draw.line([gx, gy + 5, gx + 1, gy], fill=(40, min(255, g + 30), 40), width=1)
    elif tile_type == "water":
        for i in range(3):
            wy = y + size // 4 + i * (size // 4)
            wx = x + random.randint(4, size // 2)
            draw.arc([wx, wy, wx + size // 3, wy + 6], 0, 180,
                     fill=(min(255, r + 60), min(255, g + 60), min(255, b + 60)), width=1)
    elif tile_type == "lava":
        for _ in range(4):
            lx = x + random.randint(4, size - 12)
            ly = y + random.randint(4, size - 12)
            draw.ellipse([lx, ly, lx + 8, ly + 5],
                         fill=(255, min(255, g + 80), 0, 180))


def _draw_item_icon(draw, x, y, size, item_idx, palette):
    """Draw a collectible item icon."""
    cx, cy = x + size // 2, y + size // 2
    accent = palette.get("accent", [255, 200, 50])

    items = ["gem", "potion", "coin", "key", "star", "heart"]
    item = items[item_idx % len(items)]

    if item == "gem":
        pts = []
        for i in range(6):
            angle = math.radians(i * 60 - 90)
            r = size // 3
            pts.append((cx + int(r * math.cos(angle)), cy + int(r * math.sin(angle))))
        draw.polygon(pts, fill=(accent[0], accent[1], accent[2], 255),
                     outline=(255, 255, 255, 200), width=1)
        draw.line([cx - 4, cy - 4, cx + 2, cy + 2], fill=(255, 255, 255, 120), width=2)
    elif item == "potion":
        draw.rounded_rectangle([cx - 6, cy - 2, cx + 6, cy + size // 3],
                               radius=3, fill=(220, 30, 30, 255), outline=(20, 20, 20), width=1)
        draw.rectangle([cx - 3, cy - size // 4, cx + 3, cy],
                       fill=(180, 180, 190), outline=(20, 20, 20), width=1)
    elif item == "coin":
        draw.ellipse([cx - size // 4, cy - size // 4, cx + size // 4, cy + size // 4],
                     fill=(255, 200, 50), outline=(200, 150, 0), width=2)
        draw.text((cx - 3, cy - 6), "$", fill=(200, 150, 0))
    elif item == "key":
        draw.ellipse([cx - 5, cy - size // 4, cx + 5, cy - size // 4 + 10],
                     fill=(255, 200, 50), outline=(200, 150, 0), width=2)
        draw.rectangle([cx - 2, cy - size // 4 + 10, cx + 2, cy + size // 4],
                       fill=(255, 200, 50), outline=(200, 150, 0), width=1)
    elif item == "star":
        pts = []
        for i in range(10):
            angle = math.radians(i * 36 - 90)
            r = size // 3 if i % 2 == 0 else size // 6
            pts.append((cx + int(r * math.cos(angle)), cy + int(r * math.sin(angle))))
        draw.polygon(pts, fill=(255, 220, 50, 255), outline=(200, 170, 0), width=1)
    elif item == "heart":
        r = size // 5
        draw.ellipse([cx - r * 2, cy - r, cx, cy + r], fill=(220, 30, 50))
        draw.ellipse([cx, cy - r, cx + r * 2, cy + r], fill=(220, 30, 50))
        draw.polygon([(cx - r * 2, cy), (cx, cy + r * 2), (cx + r * 2, cy)], fill=(220, 30, 50))


def generate_sprites(config, output_dir):
    """Generate sprite sheets using Pillow, plus GIMP scripts."""
    sprites_dir = os.path.join(output_dir, "sprites")
    os.makedirs(sprites_dir, exist_ok=True)

    sprite_size = config["pipeline_2d"]["sprite_size"]
    palettes = config["palettes"]
    generated = []

    # ── Character Sprite Sheets ──
    for sprite_def in config["pipeline_2d"]["sprites"]:
        name = sprite_def["name"]
        frames = sprite_def["frames"]
        palette_name = sprite_def.get("palette", "fantasy")
        palette = palettes.get(palette_name, palettes["fantasy"])
        color = palette["primary"]

        cols = min(len(frames), config["pipeline_2d"]["sprite_sheet_columns"])
        rows = math.ceil(len(frames) / cols)
        sheet_w = cols * sprite_size
        sheet_h = rows * sprite_size

        sheet = Image.new("RGBA", (sheet_w, sheet_h), (0, 0, 0, 0))
        draw = ImageDraw.Draw(sheet)

        frame_meta = []
        for i, frame_name in enumerate(frames):
            col = i % cols
            row = i // cols
            x = col * sprite_size
            y = row * sprite_size
            _draw_character_frame(draw, x, y, sprite_size, frame_name, color, variant=i)
            frame_meta.append({
                "name": frame_name,
                "x": x, "y": y,
                "width": sprite_size, "height": sprite_size
            })

        sheet_path = os.path.join(sprites_dir, f"{name}_sheet.png")
        sheet.save(sheet_path)

        meta_path = os.path.join(sprites_dir, f"{name}_meta.json")
        with open(meta_path, "w") as f:
            json.dump({
                "name": name,
                "sprite_size": sprite_size,
                "columns": cols,
                "rows": rows,
                "frames": frame_meta
            }, f, indent=2)

        generated.append({
            "type": "sprite_sheet",
            "name": f"{name}_sheet.png",
            "path": sheet_path,
            "meta_path": meta_path,
            "dimensions": f"{sheet_w}x{sheet_h}",
            "frame_count": len(frames)
        })

    # ── Tile Sets ──
    tiles_config = config["pipeline_2d"]["tiles"]
    fantasy_palette = palettes["fantasy"]
    tile_size = sprite_size

    total_tiles = sum(t.get("variants", 1) for t in tiles_config)
    cols = 4
    rows = math.ceil(total_tiles / cols)
    tileset = Image.new("RGBA", (cols * tile_size, rows * tile_size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(tileset)

    tile_idx = 0
    tile_meta = []
    for tile_def in tiles_config:
        for v in range(tile_def.get("variants", 1)):
            col = tile_idx % cols
            row = tile_idx // cols
            x = col * tile_size
            y = row * tile_size
            _draw_tile(draw, x, y, tile_size, tile_def["name"], fantasy_palette, v)
            tile_meta.append({
                "name": f"{tile_def['name']}_v{v}",
                "x": x, "y": y,
                "width": tile_size, "height": tile_size
            })
            tile_idx += 1

    tileset_path = os.path.join(sprites_dir, "tileset.png")
    tileset.save(tileset_path)

    meta_path = os.path.join(sprites_dir, "tileset_meta.json")
    with open(meta_path, "w") as f:
        json.dump({"tile_size": tile_size, "columns": cols, "rows": rows, "tiles": tile_meta}, f, indent=2)

    generated.append({
        "type": "tileset",
        "name": "tileset.png",
        "path": tileset_path,
        "meta_path": meta_path,
        "dimensions": f"{cols * tile_size}x{rows * tile_size}",
        "tile_count": total_tiles
    })

    # ── Item Icons ──
    icon_count = 6
    icon_cols = 6
    icon_rows = 1
    icons = Image.new("RGBA", (icon_cols * tile_size, icon_rows * tile_size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(icons)

    for i in range(icon_count):
        _draw_item_icon(draw, i * tile_size, 0, tile_size, i, fantasy_palette)

    icons_path = os.path.join(sprites_dir, "item_icons.png")
    icons.save(icons_path)

    generated.append({
        "type": "icon_sheet",
        "name": "item_icons.png",
        "path": icons_path,
        "dimensions": f"{icon_cols * tile_size}x{icon_rows * tile_size}",
        "icon_count": icon_count
    })

    return generated


def run(config, output_dir):
    """Main entry — generate sprites + GIMP scripts."""
    results = []
    results.extend(generate_sprites(config, output_dir))
    results.extend(generate_gimp_scripts(config, output_dir))
    return results
