"""
UI Designer — Inkscape SVG + Pillow Fallback
Generates game UI/HUD elements as Inkscape-native SVGs
and Pillow-rendered PNG previews for the dashboard.
"""
import os, json, math
from PIL import Image, ImageDraw

# ─── INKSCAPE SVG GENERATORS ──────────────────────────────────────────

SVG_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
     width="{w}" height="{h}" viewBox="0 0 {w} {h}"
     inkscape:version="1.3">
  <metadata>
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
             xmlns:dc="http://purl.org/dc/elements/1.1/">
      <rdf:Description>
        <dc:title>{title}</dc:title>
        <dc:description>Game UI element - Auto-generated by Asset Pipeline</dc:description>
      </rdf:Description>
    </rdf:RDF>
  </metadata>
  <defs>
    <linearGradient id="grad_green" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:#22c55e;stop-opacity:1"/>
      <stop offset="100%" style="stop-color:#16a34a;stop-opacity:1"/>
    </linearGradient>
    <linearGradient id="grad_blue" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:#3b82f6;stop-opacity:1"/>
      <stop offset="100%" style="stop-color:#2563eb;stop-opacity:1"/>
    </linearGradient>
    <linearGradient id="grad_purple" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:#a855f7;stop-opacity:1"/>
      <stop offset="100%" style="stop-color:#7c3aed;stop-opacity:1"/>
    </linearGradient>
    <linearGradient id="grad_red" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:#ef4444;stop-opacity:1"/>
      <stop offset="100%" style="stop-color:#dc2626;stop-opacity:1"/>
    </linearGradient>
    <linearGradient id="grad_gold" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:#fbbf24;stop-opacity:1"/>
      <stop offset="100%" style="stop-color:#f59e0b;stop-opacity:1"/>
    </linearGradient>
    <filter id="glow">
      <feGaussianBlur stdDeviation="2" result="blur"/>
      <feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
    <filter id="shadow">
      <feDropShadow dx="1" dy="2" stdDeviation="2" flood-color="#000" flood-opacity="0.5"/>
    </filter>
  </defs>
"""
SVG_FOOTER = "</svg>"

def _svg_health_bar(w, h):
    fill_w = int(w * 0.75)
    return f"""  <g inkscape:label="Health Bar" inkscape:groupmode="layer">
    <rect x="0" y="0" width="{w}" height="{h}" rx="4" fill="#1a1a2e" stroke="#333" stroke-width="1"/>
    <rect x="2" y="2" width="{fill_w}" height="{h-4}" rx="3" fill="url(#grad_red)" filter="url(#glow)"/>
    <text x="10" y="{h//2+4}" fill="white" font-family="Inter,sans-serif" font-size="10" font-weight="bold">HP 75/100</text>
    <rect x="2" y="2" width="{fill_w}" height="{(h-4)//2}" rx="3" fill="rgba(255,255,255,0.15)"/>
  </g>\n"""

def _svg_mana_bar(w, h):
    fill_w = int(w * 0.6)
    return f"""  <g inkscape:label="Mana Bar" inkscape:groupmode="layer">
    <rect x="0" y="0" width="{w}" height="{h}" rx="4" fill="#1a1a2e" stroke="#333" stroke-width="1"/>
    <rect x="2" y="2" width="{fill_w}" height="{h-4}" rx="3" fill="url(#grad_blue)" filter="url(#glow)"/>
    <text x="10" y="{h//2+4}" fill="white" font-family="Inter,sans-serif" font-size="10" font-weight="bold">MP 60/100</text>
    <rect x="2" y="2" width="{fill_w}" height="{(h-4)//2}" rx="3" fill="rgba(255,255,255,0.15)"/>
  </g>\n"""

def _svg_xp_bar(w, h):
    fill_w = int(w * 0.45)
    return f"""  <g inkscape:label="XP Bar" inkscape:groupmode="layer">
    <rect x="0" y="0" width="{w}" height="{h}" rx="3" fill="#1a1a2e" stroke="#333" stroke-width="1"/>
    <rect x="2" y="2" width="{fill_w}" height="{h-4}" rx="2" fill="url(#grad_gold)"/>
    <text x="{w//2-15}" y="{h//2+3}" fill="white" font-family="Inter,sans-serif" font-size="8">LVL 12 — 45%</text>
  </g>\n"""

def _svg_inventory_slot(w, h):
    return f"""  <g inkscape:label="Inventory Slot" inkscape:groupmode="layer">
    <rect x="0" y="0" width="{w}" height="{h}" rx="6" fill="#1e1e3a" stroke="#444" stroke-width="1.5" filter="url(#shadow)"/>
    <rect x="3" y="3" width="{w-6}" height="{h-6}" rx="4" fill="#252550" stroke="#555" stroke-width="0.5"/>
    <line x1="4" y1="{h-8}" x2="{w-4}" y2="{h-8}" stroke="#333" stroke-width="0.5"/>
    <text x="{w//2}" y="{h-3}" fill="#888" font-family="Inter,sans-serif" font-size="7" text-anchor="middle">1</text>
  </g>\n"""

def _svg_dialog_box(w, h):
    return f"""  <g inkscape:label="Dialog Box" inkscape:groupmode="layer">
    <rect x="0" y="0" width="{w}" height="{h}" rx="8" fill="#12122a" stroke="#3b82f6" stroke-width="1.5" opacity="0.95" filter="url(#shadow)"/>
    <rect x="0" y="0" width="{w}" height="30" rx="8" fill="#1e1e4a"/>
    <rect x="0" y="15" width="{w}" height="15" fill="#1e1e4a"/>
    <text x="15" y="20" fill="#e2e8f0" font-family="Inter,sans-serif" font-size="12" font-weight="bold">NPC Dialog</text>
    <line x1="10" y1="32" x2="{w-10}" y2="32" stroke="#333" stroke-width="0.5"/>
    <text x="15" y="55" fill="#a0aec0" font-family="Inter,sans-serif" font-size="10">Welcome, adventurer! I have a</text>
    <text x="15" y="70" fill="#a0aec0" font-family="Inter,sans-serif" font-size="10">quest that requires your skills...</text>
    <rect x="{w-90}" y="{h-35}" width="75" height="25" rx="4" fill="url(#grad_blue)"/>
    <text x="{w-65}" y="{h-18}" fill="white" font-family="Inter,sans-serif" font-size="10" font-weight="bold">Accept</text>
  </g>\n"""

def _svg_minimap(w, h):
    circles = ""
    for i in range(5):
        cx = 30 + i * 30
        cy = 40 + (i % 3) * 25
        circles += f'    <circle cx="{cx}" cy="{cy}" r="4" fill="#22c55e" opacity="0.7"/>\n'
    return f"""  <g inkscape:label="Minimap" inkscape:groupmode="layer">
    <rect x="0" y="0" width="{w}" height="{h}" rx="8" fill="#0a0a1a" stroke="#444" stroke-width="2"/>
    <rect x="4" y="4" width="{w-8}" height="{h-8}" rx="6" fill="#111128"/>
    <line x1="20" y1="{h//2}" x2="{w-20}" y2="{h//2}" stroke="#1a3a1a" stroke-width="0.5"/>
    <line x1="{w//2}" y1="20" x2="{w//2}" y2="{h-20}" stroke="#1a3a1a" stroke-width="0.5"/>
{circles}    <polygon points="{w//2},{h//2-6} {w//2-4},{h//2+4} {w//2+4},{h//2+4}" fill="#ef4444"/>
    <text x="8" y="{h-6}" fill="#666" font-family="Inter,sans-serif" font-size="7">N</text>
  </g>\n"""

def _svg_tooltip(w, h):
    return f"""  <g inkscape:label="Tooltip" inkscape:groupmode="layer">
    <rect x="0" y="0" width="{w}" height="{h}" rx="6" fill="#1a1a35" stroke="#a855f7" stroke-width="1" opacity="0.95" filter="url(#shadow)"/>
    <text x="10" y="20" fill="#e2e8f0" font-family="Inter,sans-serif" font-size="11" font-weight="bold">Iron Sword</text>
    <text x="10" y="36" fill="#a855f7" font-family="Inter,sans-serif" font-size="9">Uncommon Weapon</text>
    <text x="10" y="52" fill="#94a3b8" font-family="Inter,sans-serif" font-size="9">ATK +15  SPD +3</text>
    <text x="10" y="68" fill="#64748b" font-family="Inter,sans-serif" font-size="8" font-style="italic">A sturdy blade forged in fire.</text>
  </g>\n"""

SVG_BUILDERS = {
    "health_bar": _svg_health_bar, "mana_bar": _svg_mana_bar,
    "xp_bar": _svg_xp_bar, "inventory_slot": _svg_inventory_slot,
    "dialog_box": _svg_dialog_box, "minimap_frame": _svg_minimap,
    "tooltip": _svg_tooltip
}

# ─── INKSCAPE CLI EXPORT SCRIPT ──────────────────────────────────────
INKSCAPE_EXPORT_BAT = """@echo off
REM Inkscape CLI batch export — generated by Game Asset Pipeline
REM Exports SVGs to PNG at multiple DPIs
set INKSCAPE=inkscape
{commands}
echo Done.
"""

def generate_svgs(config, output_dir):
    sd = os.path.join(output_dir, "ui_assets"); os.makedirs(sd, exist_ok=True)
    gen = []; export_cmds = []
    for el in config["pipeline_2d"]["ui_elements"]:
        name, w, h = el["name"], el["width"], el["height"]
        builder = SVG_BUILDERS.get(name)
        if not builder: continue
        svg = SVG_HEADER.format(w=w, h=h, title=name.replace("_"," ").title()) + builder(w, h) + SVG_FOOTER
        sp = os.path.join(sd, f"{name}.svg")
        with open(sp, "w", encoding="utf-8") as f: f.write(svg)
        for dpi in config["pipeline_2d"]["dpi_variants"]:
            pp = os.path.join(sd, f"{name}_{dpi}dpi.png")
            export_cmds.append(f'%INKSCAPE% --export-filename="{pp}" --export-dpi={dpi} "{sp}"')
        gen.append({"type":"svg_ui","name":f"{name}.svg","path":sp,"tool":"Inkscape",
                    "dimensions":f"{w}x{h}","description":f"UI element: {name}"})
    # Write Inkscape batch export script
    bat_path = os.path.join(output_dir, "scripts", "inkscape_export.bat")
    os.makedirs(os.path.dirname(bat_path), exist_ok=True)
    with open(bat_path, "w") as f:
        f.write(INKSCAPE_EXPORT_BAT.format(commands="\n".join(export_cmds)))
    gen.append({"type":"inkscape_batch","name":"inkscape_export.bat","path":bat_path,
                "tool":"Inkscape CLI"})
    return gen

# ─── PILLOW FALLBACK PREVIEWS ────────────────────────────────────────
def _draw_bar(draw, x, y, w, h, fill_pct, colors, label):
    draw.rounded_rectangle([x,y,x+w,y+h], radius=4, fill=(26,26,46), outline=(60,60,80))
    fw = int((w-4)*fill_pct)
    if fw > 0:
        for px in range(fw):
            t = px/max(fw-1,1)
            r = int(colors[0][0]*(1-t)+colors[1][0]*t)
            g = int(colors[0][1]*(1-t)+colors[1][1]*t)
            b = int(colors[0][2]*(1-t)+colors[1][2]*t)
            draw.line([x+2+px,y+2,x+2+px,y+h-2], fill=(r,g,b))
    draw.text((x+8,y+h//2-5), label, fill=(255,255,255))

def generate_previews(config, output_dir):
    pd = os.path.join(output_dir, "ui_assets"); os.makedirs(pd, exist_ok=True)
    gen = []
    # Combined HUD preview
    img = Image.new("RGBA",(420,300),(18,18,35,255)); draw = ImageDraw.Draw(img)
    _draw_bar(draw,10,10,200,24,0.75,[(239,68,68),(220,38,38)],"HP 75/100")
    _draw_bar(draw,10,44,200,24,0.6,[(59,130,246),(37,99,235)],"MP 60/100")
    _draw_bar(draw,10,78,300,16,0.45,[(251,191,36),(245,158,11)],"XP 45%")
    # Inventory grid
    for r in range(2):
        for c in range(5):
            ix,iy = 10+c*68, 110+r*68
            draw.rounded_rectangle([ix,iy,ix+60,iy+60],radius=6,fill=(30,30,58),outline=(68,68,100))
    # Dialog box
    draw.rounded_rectangle([10,260,410,295],radius=6,fill=(18,18,42),outline=(59,130,246))
    draw.text((20,268),"Welcome adventurer! Press [E] to continue...",fill=(160,174,192))
    p = os.path.join(pd,"hud_preview.png"); img.save(p)
    gen.append({"type":"ui_preview","name":"hud_preview.png","path":p,"dimensions":"420x300"})
    return gen

def run(config, output_dir):
    return generate_svgs(config, output_dir) + generate_previews(config, output_dir)
