; ============================================================
; GIMP Script-Fu: knight Sprite Sheet Generator
; Auto-generated by Game Asset Pipeline
; Usage: gimp -i -b '(script-fu-load "output/scripts/gimp/knight_sprites.scm")' -b '(gimp-quit 0)'
; ============================================================

(define (generate-knight-sprites output-dir)
  (let* (
    (sprite-w 64)
    (sprite-h 64)
    (cols 8)
    (rows 1)
    (sheet-w (* sprite-w cols))
    (sheet-h (* sprite-h rows))
    (sheet (car (gimp-image-new sheet-w sheet-h RGB)))
    (layer (car (gimp-layer-new sheet sheet-w sheet-h RGBA-IMAGE "sprites" 100 LAYER-MODE-NORMAL)))
  )
  (gimp-image-insert-layer sheet layer 0 -1)

  ; Set foreground color for sprite base
  (gimp-context-set-foreground '(72 120 200))

  ; Draw sprite frames
  ; Frame: idle (col 0, row 0)
  (gimp-image-set-active-layer sheet layer)
  (gimp-context-set-foreground '(72 120 200))
  (gimp-edit-fill layer FILL-FOREGROUND)
  (gimp-image-select-rectangle sheet CHANNEL-OP-REPLACE 0 0 64 64)
  (gimp-edit-bucket-fill layer FILL-FOREGROUND LAYER-MODE-NORMAL 100 0 FALSE 0 0)
  (gimp-selection-none sheet)
  ; Frame: walk_1 (col 1, row 0)
  (gimp-image-set-active-layer sheet layer)
  (gimp-context-set-foreground '(72 120 200))
  (gimp-edit-fill layer FILL-FOREGROUND)
  (gimp-image-select-rectangle sheet CHANNEL-OP-REPLACE 64 0 64 64)
  (gimp-edit-bucket-fill layer FILL-FOREGROUND LAYER-MODE-NORMAL 100 0 FALSE 0 0)
  (gimp-selection-none sheet)
  ; Frame: walk_2 (col 2, row 0)
  (gimp-image-set-active-layer sheet layer)
  (gimp-context-set-foreground '(72 120 200))
  (gimp-edit-fill layer FILL-FOREGROUND)
  (gimp-image-select-rectangle sheet CHANNEL-OP-REPLACE 128 0 64 64)
  (gimp-edit-bucket-fill layer FILL-FOREGROUND LAYER-MODE-NORMAL 100 0 FALSE 0 0)
  (gimp-selection-none sheet)
  ; Frame: walk_3 (col 3, row 0)
  (gimp-image-set-active-layer sheet layer)
  (gimp-context-set-foreground '(72 120 200))
  (gimp-edit-fill layer FILL-FOREGROUND)
  (gimp-image-select-rectangle sheet CHANNEL-OP-REPLACE 192 0 64 64)
  (gimp-edit-bucket-fill layer FILL-FOREGROUND LAYER-MODE-NORMAL 100 0 FALSE 0 0)
  (gimp-selection-none sheet)
  ; Frame: attack_1 (col 4, row 0)
  (gimp-image-set-active-layer sheet layer)
  (gimp-context-set-foreground '(72 120 200))
  (gimp-edit-fill layer FILL-FOREGROUND)
  (gimp-image-select-rectangle sheet CHANNEL-OP-REPLACE 256 0 64 64)
  (gimp-edit-bucket-fill layer FILL-FOREGROUND LAYER-MODE-NORMAL 100 0 FALSE 0 0)
  (gimp-selection-none sheet)
  ; Frame: attack_2 (col 5, row 0)
  (gimp-image-set-active-layer sheet layer)
  (gimp-context-set-foreground '(72 120 200))
  (gimp-edit-fill layer FILL-FOREGROUND)
  (gimp-image-select-rectangle sheet CHANNEL-OP-REPLACE 320 0 64 64)
  (gimp-edit-bucket-fill layer FILL-FOREGROUND LAYER-MODE-NORMAL 100 0 FALSE 0 0)
  (gimp-selection-none sheet)
  ; Frame: jump (col 6, row 0)
  (gimp-image-set-active-layer sheet layer)
  (gimp-context-set-foreground '(72 120 200))
  (gimp-edit-fill layer FILL-FOREGROUND)
  (gimp-image-select-rectangle sheet CHANNEL-OP-REPLACE 384 0 64 64)
  (gimp-edit-bucket-fill layer FILL-FOREGROUND LAYER-MODE-NORMAL 100 0 FALSE 0 0)
  (gimp-selection-none sheet)
  ; Frame: fall (col 7, row 0)
  (gimp-image-set-active-layer sheet layer)
  (gimp-context-set-foreground '(72 120 200))
  (gimp-edit-fill layer FILL-FOREGROUND)
  (gimp-image-select-rectangle sheet CHANNEL-OP-REPLACE 448 0 64 64)
  (gimp-edit-bucket-fill layer FILL-FOREGROUND LAYER-MODE-NORMAL 100 0 FALSE 0 0)
  (gimp-selection-none sheet)


  ; Flatten and export
  (gimp-image-flatten sheet)
  (file-png-save RUN-NONINTERACTIVE sheet
    (car (gimp-image-get-active-drawable sheet))
    (string-append output-dir "/knight_sheet.png")
    "knight_sheet" 0 9 1 1 1 1 1)

  (gimp-image-delete sheet)
  )
)

; Execute
(generate-knight-sprites "output/sprites")
